version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    network_mode: "bridge"
    environment:
     - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
     - CLUSTERED=false
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    network_mode: "bridge"
  redis:
    image: redis
    ports:
      - "6379:6379"    
    network_mode: "bridge"
  mysqlsrv:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "testedb"
      MYSQL_USER: 'someuser'
      MYSQL_PASSWORD: 'somepassword'
    ports:
      - "3306:3306"
    network_mode: "bridge"
  accountservice:
    image: legacy-system-without-kafka/account:0.0.1-SNAPSHOT     
    ports:
      - "8081:8081"
    network_mode: "bridge"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8081"
      RABBITMQ_PORT: "5672"
      REDIS_PORT: "6379"
      MONGO_PORT: "27017"
      ACCOUNT_PORT: "8085"
    links:
      - rabbitmq
      - redis
      - mongo
      - accountlegacyservice
  accountlegacyservice:
    image: legacy-system-without-kafka/accountlegacy:0.0.1-SNAPSHOT     
    ports:
      - "8085:8085"
    network_mode: "bridge"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      RABBITMQ_PORT: "5672"
      REDIS_PORT: "6379"
      MONGO_PORT: "27017"
      MYSQL_PORT: "3306"
    links:
      - rabbitmq
      - redis
      - mongo
      - mysqlsrv
      
  catalogservice:
    image: legacy-system-without-kafka/catalog:0.0.1-SNAPSHOT     
    ports:
      - "8082:8082"
    network_mode: "bridge"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8082"
      RABBITMQ_PORT: "5672"
      REDIS_PORT: "6379"
      MONGO_PORT: "27017"
      CUSTOMER_PORT: "8080"
    links:
      - rabbitmq
      - redis
      - mongo 
      - customerservice
  customerservice:
    image: legacy-system-without-kafka/customer:0.0.1-SNAPSHOT     
    ports:
      - "8080:8080"
    network_mode: "bridge"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      RABBITMQ_PORT: "5672"
      REDIS_PORT: "6379"
      MONGO_PORT: "27017"
    links:
      - rabbitmq
      - redis
      - mongo   
      - accountservice       
  orderservice:
    image: legacy-system-without-kafka/order:0.0.1-SNAPSHOT     
    ports:
      - "8083:8083"
    network_mode: "bridge"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8083"
      RABBITMQ_PORT: "5672"
      REDIS_PORT: "6379"
      MONGO_PORT: "27017"
      CATALOG_PORT: "8082"
    links:
      - rabbitmq
      - redis
      - mongo     
      - catalogservice 
      - accountservice
