version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    network_mode: "bridge"
    environment:
     - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
     - CLUSTERED=false
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    network_mode: "bridge"
  redis:
    image: redis
    ports:
      - "6379:6379"    
    network_mode: "bridge"
  accountservice:
    image: full-cqrs-without-kafka/account:0.0.1-SNAPSHOT     
    ports:
      - "8081:8081"
    network_mode: "bridge"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8081"
      RABBITMQ_PORT: "5672"
      REDIS_PORT: "6379"
      MONGO_PORT: "27017"
      CUSTOMER_PORT: "8080"
    links:
      - rabbitmq
      - redis
      - mongo
      - customerservice
  catalogservice:
    image: full-cqrs-without-kafka/catalog:0.0.1-SNAPSHOT     
    ports:
      - "8082:8082"
    network_mode: "bridge"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8082"
      RABBITMQ_PORT: "5672"
      REDIS_PORT: "6379"
      MONGO_PORT: "27017"
      CUSTOMER_PORT: "8080"
    links:
      - rabbitmq
      - redis
      - mongo 
      - customerservice
  customerservice:
    image: full-cqrs-without-kafka/customer:0.0.1-SNAPSHOT     
    ports:
      - "8080:8080"
    network_mode: "bridge"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      RABBITMQ_PORT: "5672"
      REDIS_PORT: "6379"
      MONGO_PORT: "27017"
    links:
      - rabbitmq
      - redis
      - mongo          
  orderservice:
    image: full-cqrs-without-kafka/order:0.0.1-SNAPSHOT     
    ports:
      - "8083:8083"
    network_mode: "bridge"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8083"
      RABBITMQ_PORT: "5672"
      REDIS_PORT: "6379"
      MONGO_PORT: "27017"
      CUSTOMER_PORT: "8080"
    links:
      - rabbitmq
      - redis
      - mongo     
      - customerservice
      - catalogservice
networks: 
    mongo-compose-network:
      driver: bridge
