
package localhost.accounts;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountPortService", targetNamespace = "http://localhost/accounts/", wsdlLocation = "http://localhost:8085/ws/account.wsdl")
public class AccountPortService
    extends Service
{

    private final static URL ACCOUNTPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTPORTSERVICE_EXCEPTION;
    private final static QName ACCOUNTPORTSERVICE_QNAME = new QName("http://localhost/accounts/", "AccountPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://accountlegacyservice:8085/ws/account.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTPORTSERVICE_WSDL_LOCATION = url;
        ACCOUNTPORTSERVICE_EXCEPTION = e;
    }

    public AccountPortService() {
        super(__getWsdlLocation(), ACCOUNTPORTSERVICE_QNAME);
    }

    public AccountPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTPORTSERVICE_QNAME, features);
    }

    public AccountPortService(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTPORTSERVICE_QNAME);
    }

    public AccountPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTPORTSERVICE_QNAME, features);
    }

    public AccountPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountPort
     */
    @WebEndpoint(name = "AccountPortSoap11")
    public AccountPort getAccountPortSoap11() {
        return super.getPort(new QName("http://localhost/accounts/", "AccountPortSoap11"), AccountPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountPort
     */
    @WebEndpoint(name = "AccountPortSoap11")
    public AccountPort getAccountPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/accounts/", "AccountPortSoap11"), AccountPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTPORTSERVICE_EXCEPTION!= null) {
            throw ACCOUNTPORTSERVICE_EXCEPTION;
        }
        return ACCOUNTPORTSERVICE_WSDL_LOCATION;
    }

}
