
package localhost.accounts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountPort", targetNamespace = "http://localhost/accounts/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountPort {


    /**
     * 
     * @param getAccountRequest
     * @return
     *     returns localhost.accounts.GetAccountResponse
     */
    @WebMethod
    @WebResult(name = "getAccountResponse", targetNamespace = "http://localhost/accounts/", partName = "getAccountResponse")
    public GetAccountResponse getAccount(
        @WebParam(name = "getAccountRequest", targetNamespace = "http://localhost/accounts/", partName = "getAccountRequest")
        GetAccountRequest getAccountRequest);

    /**
     * 
     * @param updateBalanceRequest
     * @return
     *     returns localhost.accounts.UpdateBalanceResponse
     */
    @WebMethod
    @WebResult(name = "updateBalanceResponse", targetNamespace = "http://localhost/accounts/", partName = "updateBalanceResponse")
    public UpdateBalanceResponse updateBalance(
        @WebParam(name = "updateBalanceRequest", targetNamespace = "http://localhost/accounts/", partName = "updateBalanceRequest")
        UpdateBalanceRequest updateBalanceRequest);

    /**
     * 
     * @param getCustomerAccountRequest
     * @return
     *     returns localhost.accounts.GetCustomerAccountResponse
     */
    @WebMethod
    @WebResult(name = "getCustomerAccountResponse", targetNamespace = "http://localhost/accounts/", partName = "getCustomerAccountResponse")
    public GetCustomerAccountResponse getCustomerAccount(
        @WebParam(name = "getCustomerAccountRequest", targetNamespace = "http://localhost/accounts/", partName = "getCustomerAccountRequest")
        GetCustomerAccountRequest getCustomerAccountRequest);

    /**
     * 
     * @param deleteAccountRequest
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(name = "deleteAccountResponse", targetNamespace = "http://localhost/accounts/", partName = "deleteAccountResponse")
    public Object deleteAccount(
        @WebParam(name = "deleteAccountRequest", targetNamespace = "http://localhost/accounts/", partName = "deleteAccountRequest")
        DeleteAccountRequest deleteAccountRequest);

    /**
     * 
     * @param createAccountRequest
     * @return
     *     returns localhost.accounts.CreateAccountResponse
     */
    @WebMethod
    @WebResult(name = "createAccountResponse", targetNamespace = "http://localhost/accounts/", partName = "createAccountResponse")
    public CreateAccountResponse createAccount(
        @WebParam(name = "createAccountRequest", targetNamespace = "http://localhost/accounts/", partName = "createAccountRequest")
        CreateAccountRequest createAccountRequest);

}
